export const fakeSeasons = [
  {
    season: 1,
    episodes: [
      { episode: 1, title: "Pilot", rating: 8.3 },
      { episode: 2, title: "Cat's in the Bag...", rating: 8.1 },
      { episode: 3, title: "...And the Bag's in the River", rating: 8.5 },
      { episode: 4, title: "Cancer Man", rating: 8.0 },
      { episode: 5, title: "Gray Matter", rating: 7.9 },
      { episode: 6, title: "Crazy Handful of Nothin'", rating: 8.7 },
      { episode: 7, title: "A No-Rough-Stuff-Type Deal", rating: 8.6 },
    ],
  },
  {
    season: 2,
    episodes: [
      { episode: 1, title: "Seven Thirty-Seven", rating: 8.4 },
      { episode: 2, title: "Grilled", rating: 8.8 },
      { episode: 3, title: "Bit by a Dead Bee", rating: 8.2 },
      { episode: 4, title: "Down", rating: 8.3 },
      { episode: 5, title: "Breakage", rating: 8.5 },
      { episode: 6, title: "Peekaboo", rating: 8.6 },
      { episode: 7, title: "Negro y Azul", rating: 8.9 },
      { episode: 8, title: "Better Call Saul", rating: 8.7 },
      { episode: 9, title: "4 Days Out", rating: 8.8 },
      { episode: 10, title: "Over", rating: 8.4 },
      { episode: 11, title: "Mandala", rating: 8.5 },
      { episode: 12, title: "Phoenix", rating: 8.6 },
      { episode: 13, title: "ABQ", rating: 8.9 },
    ],
  },
  {
    season: 3,
    episodes: [
      { episode: 1, title: "No Más", rating: 8.5 },
      { episode: 2, title: "Caballo Sin Nombre", rating: 8.4 },
      { episode: 3, title: "I.F.T.", rating: 8.3 },
      { episode: 4, title: "Green Light", rating: 8.7 },
      { episode: 5, title: "Más", rating: 8.8 },
      { episode: 6, title: "Sunset", rating: 8.6 },
      { episode: 7, title: "One Minute", rating: 9.0 },
      { episode: 8, title: "I See You", rating: 8.9 },
      { episode: 9, title: "Kafkaesque", rating: 8.7 },
      { episode: 10, title: "Fly", rating: 7.9 },
      { episode: 11, title: "Abiquiu", rating: 8.2 },
      { episode: 12, title: "Half Measures", rating: 8.8 },
      { episode: 13, title: "Full Measure", rating: 8.9 },
    ],
  },
  {
    season: 4,
    episodes: [
      { episode: 1, title: "No Más", rating: 8.5 },
      { episode: 2, title: "Caballo Sin Nombre", rating: 8.4 },
      { episode: 3, title: "I.F.T.", rating: 8.3 },
      { episode: 4, title: "Green Light", rating: 8.7 },
      { episode: 5, title: "Más", rating: 8.8 },
      { episode: 6, title: "Sunset", rating: 8.6 },
      { episode: 7, title: "One Minute", rating: 9.0 },
      { episode: 8, title: "I See You", rating: 8.9 },
      { episode: 9, title: "Kafkaesque", rating: 8.7 },
      { episode: 10, title: "Fly", rating: 7.9 },
      { episode: 11, title: "Abiquiu", rating: 8.2 },
      { episode: 12, title: "Half Measures", rating: 8.8 },
      { episode: 13, title: "Full Measure", rating: 8.9 },
    ],
  },
  {
    season: 4,
    episodes: [
      { episode: 1, title: "No Más", rating: 8.5 },
      { episode: 2, title: "Caballo Sin Nombre", rating: 8.4 },
      { episode: 3, title: "I.F.T.", rating: 8.3 },
      { episode: 4, title: "Green Light", rating: 8.7 },
      { episode: 5, title: "Más", rating: 8.8 },
      { episode: 6, title: "Sunset", rating: 8.6 },
      { episode: 7, title: "One Minute", rating: 9.0 },
      { episode: 8, title: "I See You", rating: 8.9 },
      { episode: 9, title: "Kafkaesque", rating: 8.7 },
      { episode: 10, title: "Fly", rating: 7.9 },
      { episode: 11, title: "Abiquiu", rating: 8.2 },
      { episode: 12, title: "Half Measures", rating: 8.8 },
      { episode: 13, title: "Full Measure", rating: 8.9 },
    ],
  },
  {
    season: 4,
    episodes: [
      { episode: 1, title: "No Más", rating: 4 },
      { episode: 2, title: "Caballo Sin Nombre", rating: 8.4 },
      { episode: 3, title: "I.F.T.", rating: 8.3 },
      { episode: 4, title: "Green Light", rating: 8.7 },
      { episode: 5, title: "Más", rating: 8.8 },
      { episode: 6, title: "Sunset", rating: 8.6 },
      { episode: 7, title: "One Minute", rating: 9.0 },
      { episode: 8, title: "I See You", rating: 8.9 },
      { episode: 9, title: "Kafkaesque", rating: 8.7 },
      { episode: 10, title: "Fly", rating: 6 },
      { episode: 11, title: "Abiquiu", rating: 8.2 },
      { episode: 12, title: "Half Measures", rating: 8.8 },
      { episode: 13, title: "Full Measure", rating: 8.9 },
    ],
  },
];
